export {appLanguage}

import { weatherFacts } from "./facts.js";

const $TITLE_CURRENT_HUMIDITY = document.getElementById('title-current-humidity');
const $TITLE_CURRENT_WIND = document.getElementById('title-current-wind');
const $TITLE_CURRENT_RAIN = document.getElementById('title-current-rain');
const $TITLE_CURRENT_APPARENT_TEMP = document.getElementById('title-current-apparent-temperature');
const $TITLE_TODAY_TEMPERATURE = document.getElementById('title-today-temperature');
const $TITLE_DID_YOU_KNOW = document.getElementById('title-did-you-know');
// const $TITLE_FUN_WEATHER_FACTS = document.getElementById('title-fun-weather-facts');
// const $TITLE_FOUR_DAYS_PRONOSTIC = document.getElementById('title-four-days-pronostic');

const languages = {
        english: {
                temperature: 'Temperature',
                humidity: 'Humidity',
                wind: 'Wind',
                rain: 'Rain',
                apparentTemp: 'Feels Like',
                todayTemp: 'Today\'s Temperature',
                didYouKnow: 'Did you know',
                facts: weatherFacts.english,
                weatherCodeDescription: {
                        0: 'Clear sky',
                        1: 'Mainly clear',
                        2: 'Partly cloudy',
                        3: 'Overcast',
                        45: 'Fog',
                        48: 'Depositing rime fog',
                        51: 'Drizzle: Light intensity',
                        53: 'Drizzle: Moderate intensity',
                        55: 'Drizzle: Dense intensity',
                        56: 'Freezing Drizzle: Light intensity',
                        57: 'Freezing Drizzle: Dense intensity',
                        61: 'Rain: Slight intensity',
                        63: 'Rain: Moderate intensity',
                        65: 'Rain: Heavy intensity',
                        66: 'Freezing Rain: Light intensity',
                        67: 'Freezing Rain: Heavy intensity',
                        71: 'Snow fall: Slight intensity',
                        73: 'Snow fall: Moderate intensity',
                        75: 'Snow fall: Heavy intensity',
                        77: 'Snow grains',
                        80: 'Rain showers: Slight',
                        81: 'Rain showers: Moderate',
                        82: 'Rain showers: Violent',
                        85: 'Snow showers: Slight',
                        86: 'Snow showers: Heavy',
                        95: 'Thunderstorm: Slight or moderate',
                        96: 'Thunderstorm with slight hail',
                        99: 'Thunderstorm with heavy hail'
                }
        },
        spanish: {
                temperature: 'Temperatura',
                humidity: 'Humedad',
                wind: 'Viento',
                rain: 'Lluvia',
                apparentTemp: 'Sensación',
                todayTemp: 'Temperatura de hoy',
                didYouKnow: 'Sabías que',
                facts: weatherFacts.spanish,
                weatherCodeDescription: {
                        0: 'Despejado',
                        1: 'Principalmente despejado',
                        2: 'Parcialmente nublado',
                        3: 'Nublado',
                        45: 'Niebla',
                        48: 'Niebla con escarcha depositada',
                        51: 'Llovizna: Intensidad ligera',
                        53: 'Llovizna: Intensidad moderada',
                        55: 'Llovizna: Intensidad densa',
                        56: 'Llovizna congelante: Intensidad ligera',
                        57: 'Llovizna congelante: Intensidad densa',
                        61: 'Lluvia: Intensidad ligera',
                        63: 'Lluvia: Intensidad moderada',
                        65: 'Lluvia: Intensidad fuerte',
                        66: 'Lluvia congelante: Intensidad ligera',
                        67: 'Lluvia congelante: Intensidad fuerte',
                        71: 'Nevada: Intensidad ligera',
                        73: 'Nevada: Intensidad moderada',
                        75: 'Nevada: Intensidad fuerte',
                        77: 'Granos de nieve',
                        80: 'Chubascos: Ligeros',
                        81: 'Chubascos: Moderados',
                        82: 'Chubascos: Violentos',
                        85: 'Chubascos de nieve: Ligeros',
                        86: 'Chubascos de nieve: Fuertes',
                        95: 'Tormenta eléctrica: Ligera o moderada',
                        96: 'Tormenta eléctrica con granizo ligero',
                        99: 'Tormenta eléctrica con granizo fuerte'
                }
        },
        // RUSSIAN TRANSLATE GENERATED BY CHAT GPT. COULD BE WRONG.
        russian: {
                temperature: 'Температура',
                humidity: 'Влажность',
                wind: 'Ветер',
                rain: 'Дождь',
                apparentTemp: 'Ощущаемая температура',
                todayTemp: 'Температура сегодня',
                funWeatherFacts: 'Интересные факты о погоде',
                facts: weatherFacts.english,
                weatherCodeDescription: {
                        0: 'Ясно',
                        1: 'В основном ясно',
                        2: 'Малооблачно',
                        3: 'Пасмурно',
                        45: 'Туман',
                        48: 'Туман с изморозью',
                        51: 'Морось: Легкая интенсивность',
                        53: 'Морось: Умеренная интенсивность',
                        55: 'Морось: Сильная интенсивность',
                        56: 'Ледяная морось: Легкая интенсивность',
                        57: 'Ледяная морось: Сильная интенсивность',
                        61: 'Дождь: Легкая интенсивность',
                        63: 'Дождь: Умеренная интенсивность',
                        65: 'Дождь: Сильная интенсивность',
                        66: 'Ледяной дождь: Легкая интенсивность',
                        67: 'Ледяной дождь: Сильная интенсивность',
                        71: 'Снегопад: Легкая интенсивность',
                        73: 'Снегопад: Умеренная интенсивность',
                        75: 'Снегопад: Сильная интенсивность',
                        77: 'Снежная крупа',
                        80: 'Ливни: Легкие',
                        81: 'Ливни: Умеренные',
                        82: 'Ливни: Сильные',
                        85: 'Снежные ливни: Легкие',
                        86: 'Снежные ливни: Сильные',
                        95: 'Гроза: Легкая или умеренная',
                        96: 'Гроза с легким градом',
                        99: 'Гроза с сильным градом'
                }
        }
}

function setAppLanguage(language) {
        // TODO TRY AND CATCH
        $TITLE_CURRENT_HUMIDITY.innerText = appLanguage.humidity;
        $TITLE_CURRENT_WIND.innerText = appLanguage.wind;
        $TITLE_CURRENT_RAIN.innerText = appLanguage.rain;
        $TITLE_CURRENT_APPARENT_TEMP.innerText = appLanguage.apparentTemp;
        $TITLE_TODAY_TEMPERATURE.innerText = appLanguage.todayTemp;
        $TITLE_DID_YOU_KNOW.innerText = appLanguage.didYouKnow;
        // $TITLE_FUN_WEATHER_FACTS.innerText = appLanguage.funWeatherFacts;
        // $TITLE_FOUR_DAYS_PRONOSTIC.innerText = appLanguage;
}

const browserLanguage = navigator.language.slice(0, 2);
let appLanguage = languages.english;
if (browserLanguage === 'es') {
        appLanguage = languages.spanish;
} else if (browserLanguage === 'ru') {
        appLanguage = languages.russian;
}

setAppLanguage(appLanguage);


